apiVersion: v1
kind: Pod
metadata:
  name: silver-debug
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: silver-data
          mountPath: /data/silver
  volumes:
    - name: silver-data
      persistentVolumeClaim:
        claimName: spark-silver-pvc
